<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-0GIKARJ" name="tests.ShoppingCartTests" tests="3" failures="1" timestamp="2020-06-03T13:57:36 CEST" time="40.222" errors="0">
  <testcase name="asNotLoggedInUserIShallNotProceedToCheckout" time="13.490" classname="tests.ShoppingCartTests">
    <skipped/>
  </testcase> <!-- asNotLoggedInUserIShallNotProceedToCheckout -->
  <testcase name="asNotLoggedInUserIShallNotProceedToCheckout" time="7.927" classname="tests.ShoppingCartTests">
    <failure type="java.lang.AssertionError" message="Element text was &lt;You must sign on before attempting to check out. Please sign on and try checking out again.&gt; expecting to be &lt;DYou must sign on before attempting to check out. Please sign on and try checking out again.&gt;!">
      <![CDATA[java.lang.AssertionError: Element text was <You must sign on before attempting to check out. Please sign on and try checking out again.> expecting to be <DYou must sign on before attempting to check out. Please sign on and try checking out again.>!
at page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:65)
at tests.ShoppingCartTests.asNotLoggedInUserIShallNotProceedToCheckout(ShoppingCartTests.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- asNotLoggedInUserIShallNotProceedToCheckout -->
  <testcase name="asNotLoggedInUserIShallNotProceedToCheckout" time="18.805" classname="tests.ShoppingCartTests">
    <skipped/>
  </testcase> <!-- asNotLoggedInUserIShallNotProceedToCheckout -->
</testsuite> <!-- tests.ShoppingCartTests -->
